version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /app
    steps:
      - run:
          command: pwd
      - run:
          command: ls -al
      - checkout
      - setup_remote_docker
      - run:
          command: docker version
