version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /app
    steps:
      - run:
          command: apt-get update && apt-get install -y python python-pip
      - run:
          command: pip install awscli
      - run:
          command: aws ecr get-login --no-include-email --region ap-northeast-1
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin        
      - run:
          command: docker version
