version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /app
    steps:
      - run:
          command: DOCKER_TAGNAME=$CIRCLE_BRANCH
      - run:
          command: echo $DOCKER_TAGNAME
      - run:
          command: apt-get update && apt-get install -y python-dev python-pip
      - run:
          command: pip install awscli
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin        
      - run:
          command: $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - checkout
      - run:
          command: docker build -t $DOCKER_TAGNAM .
      - run:
          command: docker tag nk-api:$DOCKER_TAGNAME 322011321453.dkr.ecr.ap-northeast-1.amazonaws.com/nk-api:$DOCKER_TAGNAME
      - run:
          command: docker push 322011321453.dkr.ecr.ap-northeast-1.amazonaws.com/nk-api:$DOCKER_TAGNAME
